import { Metadata } from "next";
import Image from "next/image";
import SignInForm from "@/app/signin/login-form";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

export default function SignIn() {
  return (
    <>
      <div className="flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8">
        <div className="w-full max-w-lg sm:mx-auto">
          <Image
            className="mx-auto h-20 w-20"
            src="https://tailwindui.com/img/logos/mark.svg?color=cyan&shade=700"
            alt="Your Company"
            width={32}
            height={32}
            unoptimized
          />
          <h2 className="mt-6 text-center text-2xl font-bold leading-9 tracking-tight text-neutral-900">
            Sign in to your account
          </h2>
        </div>

        <div className="mt-10 w-full max-w-lg sm:mx-auto">
          <div className="bg-white px-6 py-12 shadow sm:rounded-lg sm:px-12">
            <SignInForm />
          </div>
        </div>
      </div>
    </>
  );
}
